version: '1'
services:
  frontend_debug:
    build:
      context: .
      dockerfile: dockerfile.debug
      network: host
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
